controller_names:
  - joint_trajectory_controller
  - gripper_trajectory_controller
  - camera_trajectory_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - torso_lift_joint
    - shoulder_pan_joint
    - shoulder_lift_joint
    - upperarm_roll_joint
    - elbow_flex_joint
    - forearm_roll_joint
    - wrist_flex_joint
    - wrist_roll_joint

gripper_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - l_gripper_finger_joint
    - r_gripper_finger_joint

camera_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - l_wheel_joint
    - r_wheel_joint
    - bellows_joint
    - head_pan_joint
    - head_tilt_joint