controller_names:
  - joint_trajectory_controller
  - gripper_trajectory_controller
  # - gripper_action_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - upperarm_roll_joint
    - elbow_flex_joint
    - forearm_roll_joint
    - wrist_flex_joint
    - wrist_roll_joint    

gripper_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - l_gripper_finger_joint
    - r_gripper_finger_joint

# ----- Gripper action controller (not yet functional)
# gripper_action_controller:
#   action_ns: gripper_cmd
#   type: GripperCommand
#   default: true
#   joints:
#     - panda_finger_joint1
#
# Note: Once implemented, the following config needs to be within controller parameters
# controller_manager:
#   ros__parameters:
#     gripper_action_controller:
#       type: position_controllers/GripperActionController
# gripper_action_controller:
#   ros__parameters:
#     joint: panda_finger_joint1
#
# Node: Remember to enable mimicking of finger joints before attempting to use gripper action
